// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbaufxzqlvvbwmqxjrxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiYXVmeHpxbHZ2YndtcXhqcnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODU1MDgsImV4cCI6MjA2MzQ2MTUwOH0.8KqkBZH5i6Y7NS6k-LgCDeA30FdIMqhVHus6rgg9hls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);